apps/cart/urls.py
from django.urls import path
from apps.cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    path('add', CartAddView.as_view(), name='add'),  # 购物车的添加
    path('update', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    path('delete', CartDeleteView.as_view(), name='delete'),  # 购物车商品删除
    path('', CartInfoView.as_view(), name='show'),  # 购物车显示
]

apps/goods/urls.py
from django.urls import path, re_path
from apps.goods.views import IndexView, DetailView, ListView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 首页
    re_path(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    re_path(r'^goods/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list')  # 列表页
]

apps/order/urls.py
from django.urls import path, re_path
from apps.order.views import OrderPlaceView, OrderCommitView, OrderPayView, CheckPayView, CommentView

urlpatterns = [
    path('place', OrderPlaceView.as_view(), name='place'),  # 提交订单
    path('commit', OrderCommitView.as_view(), name='commit'),  # 订单创建
    path('pay', OrderPayView.as_view(), name='pay'),  # 订单支付
    path('check', CheckPayView.as_view(), name='check'),  # 查询订单结果
    re_path(r'^comment/(?P<order_id>\d+)$', CommentView.as_view(), name='comment')  # 评论
]

apps/user/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView

urlpatterns = [
    # path('register', views.register, name='register'),  # 注册
    # path('register_handle', views.register_handle, name='register_handle'),  # 注册处理
    # 调试时，查看内部方法，点击方法按ctrl键
    path('register', RegisterView.as_view(), name='register'),  # 注册
    re_path(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 用户激活

    path('login', LoginView.as_view(), name='login'),  # 登录
    path('logout', LogoutView.as_view(), name='logout'),  # 注销登录

    # path('', login_required(UserInfoView.as_view()), name='user'),  # 用户中心-信息页
    # path('order', login_required(UserOrderView.as_view()), name='order'),  # 用户中心-订单页
    # path('address', login_required(AddressView.as_view()), name='address'),  # 用户中心-地址页

    path('', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    re_path(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    path('address', AddressView.as_view(), name='address'),  # 用户中心-地址页
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import include, path

# django2.0以上版本的反向解析配置方式
urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search/', include('haystack.urls')),  # 全文检索框架
    path('cart/', include(('apps.cart.urls', "apps.cart"), namespace='cart')),  # 购物车模块
    path('order/', include(('apps.order.urls', "apps.order"), namespace='order')),  # 订单模块
    path('user/', include(('apps.user.urls', "apps.user"), namespace='user')),  # 用户模块
    path('', include(('apps.goods.urls', "apps.goods"), namespace='goods')),  # 商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequestMixin

# Create your views here.
"""
添加商品到购物车：
1）请求方式：采用ajax， post
如果涉及到数据的增删改查，采用post
2）如果只涉及到数据的获取，采用get
3）传递参数：商品id(sku_id), 商品数量(count)
"""


# /cart/add
class CartAddView(View):
    """购物车记录添加"""
    def post(self, request):
        """购物车商品的添加"""
        user = request.user
        # 判断用户是否登录
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        if not all([sku_id, count]):
            # 数据不完整
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 检验添加的商品数目
        try:
            count = int(count)
        except Exception as e:
            # 商品数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：购物车添加
        # 链接redis数据库进行添加或查询已有添加
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值，--> hget cart_key 属性
        cart_count = conn.hget(cart_key, sku_id)
        # 如果sku_id在hash中不存在则返回None
        if cart_count:
            # 累加购物车中的数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置hash中sku_id对应的值
        # hash --> 如果sku_id已经存在，更新数据，不存在进行添加
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车商品的条目
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


class CartInfoView(LoginRequestMixin, View):
    """购物车页面显示"""
    def get(self, request):
        """购物车显示"""
        # 获取登录的用户
        user = request.user
        # 获取用户购物车中的商品信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # {'商品id':商品数目}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_price = 0
        total_count = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price*int(count)
            # 动态给sku对象添加amount属性，保存商品小计
            sku.amount = amount
            # 动态给sku指定count属性，保存购物车数量
            sku.count = int(count)
            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价钱
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus
        }

        # 传递参数，返回应答
        return render(request, 'cart.html', context)


"""
    更新购物车信息
    采用ajax post 请求
    前端需要传递的信息，商品id(sku_id) 更新商品数目(count)
"""


# /cart/update
class CartUpdateView(View):
    """购物车信息更新"""
    def post(self, request):
        # 用户登录信息
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数量出错'})

        # 检验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：更新记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 判断库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        #  更新记录
        conn.hset(cart_key, sku_id, count)

        # 统计商品的总件数{'1':5, '2':3} 8件
        values = conn.hvals(cart_key)
        total_count = 0
        for value in values:
            total_count += int(value)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


"""
    前端删除购物车记录
    采用ajax post请求
    前端传递参数：商品id
"""
# /cart/delete
class CartDeleteView(View):
    """购物车记录删除"""
    def post(self, request):
        # 用户登录信息
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')

        #  数据的校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品'})

        # 检验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理：商品记录删除
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算商品的总件数
        values = conn.hvals(cart_key)
        total_count = 0
        for value in values:
            total_count += int(value)

        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})

templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
        {# 网页顶部引入js文件块 #}
    {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜素信息块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{% block body %}
    {# 网页主题内容块 #}
{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="{% url 'goods:index' %}">关于我们</a>
			<span>|</span>
			<a href="{% url 'goods:index' %}">联系我们</a>
			<span>|</span>
			<a href="{% url 'goods:index' %}">招聘人才</a>
			<span>|</span>
			<a href="{% url 'goods:index' %}">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom%}
    {# 网页底部引入的文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_user_center.html
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜—用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order'%}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容块 #}
        {% block right_content %}{% endblock right_content%}
    </div>
{% endblock body%}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for pro_banner in promotion_banners %}
			    <a href="{% url 'goods:index' %}"><img src="{{ pro_banner.image.url }}"></a>
			{% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
                <li>
                    <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                    <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                    <div class="prize">¥ {{ banner.sku.price }}</div>
                </li>
                {% endfor %}
            </ul>
		</div>
	</div>
    {% endfor %}

{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model02">海鲜水产</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">河虾</a>#}
{#				<a href="#">扇贝</a>				#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">青岛野生海捕大青虾</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods018.jpg' %}"></a>#}
{#					<div class="prize">¥ 48.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">扇贝</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods019.jpg' %}"></a>#}
{#					<div class="prize">¥ 46.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">冷冻秋刀鱼</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods020.jpg' %}"></a>#}
{#					<div class="prize">¥ 19.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">基围虾</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods021.jpg' %}"></a>#}
{#					<div class="prize">¥ 25.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model03">猪牛羊肉</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">精选前腿肉</a>#}
{#				<a href="#">牛排</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">精选前腿肉</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods022.png' %}"></a>#}
{#					<div class="prize">¥ 19.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">精选牛排</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods023.png' %}"></a>#}
{#					<div class="prize">¥ 48.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">澳洲牛排</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods024.png' %}"></a>#}
{#					<div class="prize">¥ 48.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">羊排</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods025.png' %}"></a>#}
{#					<div class="prize">¥ 58.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model04">禽类蛋品</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">土鸡蛋</a>#}
{#				<a href="#">冷冻鸡腿</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">溏心鸡蛋</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods026.png' %}"></a>#}
{#					<div class="prize">¥ 18.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">冷冻鸡肉</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods027.png' %}"></a>#}
{#					<div class="prize">¥ 15.90</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">鸡块</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods028.png' %}"></a>#}
{#					<div class="prize">¥ 9.90</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">香辣鸭舌</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods029.png' %}"></a>#}
{#					<div class="prize">¥ 38.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model05">新鲜蔬菜</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">番茄</a>#}
{#				<a href="#">甜南瓜</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">番茄</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods030.png' %}"></a>#}
{#					<div class="prize">¥ 4.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">红辣椒</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods031.png' %}"></a>#}
{#					<div class="prize">¥ 8.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">竹笋</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods032.png' %}"></a>#}
{#					<div class="prize">¥ 16.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">甜南瓜</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods033.png' %}"></a>#}
{#					<div class="prize">¥ 6.00</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="list_model">#}
{#		<div class="list_title clearfix">#}
{#			<h3 class="fl" id="model06">速冻食品</h3>#}
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">山东水饺</a>#}
{#				<a href="#">熊猫馒头</a>#}
{#			</div>#}
{#			<a href="#" class="goods_more fr">查看更多 ></a>#}
{#		</div>#}
{##}
{#		<div class="goods_con clearfix">#}
{#			<div class="goods_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>#}
{#			<ul class="goods_list fl">#}
{#				<li>#}
{#					<h4><a href="#">山东水饺</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods034.png' %}"></a>#}
{#					<div class="prize">¥ 18.90</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#"></a>放心油条</h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods035.png' %}"></a>#}
{#					<div class="prize">¥ 14.90</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">牛肉丸</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods036.png' %}"></a>#}
{#					<div class="prize">¥ 15.00</div>#}
{#				</li>#}
{#				<li>#}
{#					<h4><a href="#">熊猫馒头</a></h4>#}
{#					<a href="#"><img src="{% static 'images/goods/goods037.png' %}"></a>#}
{#					<div class="prize">¥ 9.90</div>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#	</div>#}

{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_sku %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				<li>
                    {% for sku in sku_page %}
					<a href="{% ulr 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
                    {% endfor %}
				</li>
			</ul>

			<div class="pagenation">
                {% if sku_page.has_previous%}
				    <a href="{% url 'goods:list' type.id sku_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == sku_page.number %}
				    <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				    <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if sku_page.has_next %}
				    <a href="{% url 'goods:list' type.id sku_page.previous_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}